// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjB2eeidCArejWwAlPtvTVeX_nnb0xZKM',
    appId: '1:574151433946:web:2a99dd88dfc610d5194fe3',
    messagingSenderId: '574151433946',
    projectId: 'portfolio-8ed95',
    authDomain: 'portfolio-8ed95.firebaseapp.com',
    storageBucket: 'portfolio-8ed95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbi5amg2CiWbasmXJjz8S1Hm6ceYD0Z0I',
    appId: '1:574151433946:android:d80797bbf1974f72194fe3',
    messagingSenderId: '574151433946',
    projectId: 'portfolio-8ed95',
    storageBucket: 'portfolio-8ed95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfY9wgk150Lxpm7EnyHHfsO5bYNCMHN0E',
    appId: '1:574151433946:ios:f0b67c34cfde78eb194fe3',
    messagingSenderId: '574151433946',
    projectId: 'portfolio-8ed95',
    storageBucket: 'portfolio-8ed95.firebasestorage.app',
    iosBundleId: 'com.abubakar.portfolio.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfY9wgk150Lxpm7EnyHHfsO5bYNCMHN0E',
    appId: '1:574151433946:ios:f0b67c34cfde78eb194fe3',
    messagingSenderId: '574151433946',
    projectId: 'portfolio-8ed95',
    storageBucket: 'portfolio-8ed95.firebasestorage.app',
    iosBundleId: 'com.abubakar.portfolio.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjB2eeidCArejWwAlPtvTVeX_nnb0xZKM',
    appId: '1:574151433946:web:628d8b3268931577194fe3',
    messagingSenderId: '574151433946',
    projectId: 'portfolio-8ed95',
    authDomain: 'portfolio-8ed95.firebaseapp.com',
    storageBucket: 'portfolio-8ed95.firebasestorage.app',
  );
}
